name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.4.0
      env:
        CIBW_SKIP: "cp36-* cp37-* *-win32 *_i686 pp*"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wheelhouse/*.whl
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: "wheelhouse/*.whl"


  publish:
    name: Upload ${{ matrix.artname }} wheels to PyPI
    runs-on: ubuntu-20.04
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.artname }}

    - run : ls -R

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_BIOSAUR2 }}
        verbose: true
        print_hash: true
        packages_dir: "."
