name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.4.0
      env:
        CIBW_SKIP: "cp36-* cp37-* *-win32 *_i686 pp*"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wheelhouse/*.whl
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_BIOSAUR2 }}
        packages_dir: wheelhouse
        verbose: true
        print_hash: true
